### ISSUE TITLE
Scopes: Should we require scopes/ranges to be properly nested (i.e. disallow straddling)

### ISSUE THREAD

**Issue by szuend** [tc39/source-map-rfc#73]
While the start/end item encoding enforces a tree structure, negative column deltas could still result in scopes that are not properly nested, e.g.:

```
 A |
   |
   |   B |
   |     |
   |     |
         |
         |
```

Could be encoded as `start item A`, `start item B`, 'end item B`, `end item A` where `end item A` has a negative column delta.

Should consumers reject scopes encoding like these?

**Comment by nicolo-ribaudo** [comment]
Could we maybe enforce that the delta is positive in the format itself, by storing it as an `uint` rather than as a signed integer?

**Comment by hbenl** [comment]
I agree that we should require proper nesting. It is somewhat implicit because the scopes that we are encoding need to be properly nested themselves but we could state this explicitly and also require that consumers reject a sourcemap with scopes that aren't properly nested.

> Could we maybe enforce that the delta is positive in the format itself, by storing it as an uint rather than as a signed integer?

I don't see how since we're using VLQ, which (AFAIK) doesn't have a way to encode `uint`s.

**Comment by rakudrama** [comment]
Consider allowing sibling source scopes to overlap.

Sometimes a language element is a shorthand or semantically equivalent to several elements that would normally have scopes.

In Dart, fields have an implied getter and setter. The implied getters and setters can raise exceptions, so may be on the top of the stack, or deeper, in the case of lazy initialization.

The single instance field declaration
```dart
  final late int x;
```
corresponds to two instance methods with different names and variables
* An implicit getter: a callable scope with name `x` and one variable `this`.
* An implicit setter: a callable scope with name `x=` and variables `this` and `value`.

 The implementation is not specified, but might be something like this:
```dart
  bool _xIsSet = false;
  int _x = 0;
  int get x {
    if (_xIsSet) return _x;
    throw LateError('x has not had an initializing assignment');
  }
  void set x(int value) {  // under some circumstances there might be a runtime type check here that fails.
    if (_xIsSet) throw LateError('x has already been assigned');
    _xIsSet = true;
    _x = value;
  }
```
One might make these frames hidden, but getters and setters can be the target of indirect calls, so hiding the frame would cause confusion as to which implementation was throwing. So the scopes for both setters need to map to the same source declaration.

**Comment by szuend** [comment]
I would have expected to not emit an original scope for `finale late int x;` at all, assuming this is what the user writes. If the user then reads/writes to `x` and the implicit getter/setter throw, I would expect the debugger to not show any of the generated getter/setter code but rather just have the read/write access to `x` as the top-most frame.

The current proposal would do this by emitting a "generated range" for the implicit getter/setter functions that don't have a corresponding original scope at all.

But maybe I misunderstood the example?

**Comment by rakudrama** [comment]
The synthetic scopes are useful because of indirect calls.

For more context, consider this Dart program.
It contains both synthesized accessors  (`late final` field) and hand-written accessors.
```dart
abstract interface class Box<T> {
  T get x;
  void set x(T value);
}

class LateIntBox implements Box<int> {
  late final int x;   // our instance field declaration from above
}

class NullBox<T> implements Box<T> {
  T get x => null as T;    // throws, unless `T` is a nullable type
  void set x(T value) {}
}

void demo(Object ob) {
  print('---- $ob');
  final List<Box<Object>> boxes = [LateIntBox(), NullBox<String>()];
  for (final b in boxes) {
    try {
      b.x = ob;                           // 20:9
      print('b.x = ob;');
    } catch (error, stack) {
      print(error);
      print(stack);
    }
    try {
      print('b.x has value ${b.x}');     // 27:32
    } catch (error, stack) {
      print(error);
      print(stack);
    }
  }
}

void main() {
  demo(123);
  demo('xyz');
}
```
All four getters / setters can throw.
The getter and setter calls at 20:9 and 27:32 are indirect, so for full comprehension of the stack trace, the indirect target should not be hidden. 

The Dart VM does not hide these frames (`dart /tmp/sm73.dart`) :
```
---- 123
b.x = ob;
b.x has value 123
type 'int' is not a subtype of type 'String' of 'value'
#0      NullBox.x= (file:///tmp/sm73.dart:12:16)
#1      demo (file:///tmp/sm73.dart:20:9)
#2      main (file:///tmp/sm73.dart:36:3)

type 'Null' is not a subtype of type 'String' in type cast
#0      NullBox.x (file:///tmp/sm73.dart:11:19)
#1      demo (file:///tmp/sm73.dart:27:32)
#2      main (file:///tmp/sm73.dart:36:3)

---- xyz
type 'String' is not a subtype of type 'int' of 'value'
#0      LateIntBox.x= (file:///tmp/sm73.dart:7:18)
#1      demo (file:///tmp/sm73.dart:20:9)
#2      main (file:///tmp/sm73.dart:37:3)

LateInitializationError: Field 'x' has not been initialized.
#0      LateIntBox.x (file:///tmp/sm73.dart)
#1      demo (file:///tmp/sm73.dart:27:32)
#2      main (file:///tmp/sm73.dart:37:3)

b.x = ob;
type 'Null' is not a subtype of type 'String' in type cast
#0      NullBox.x (file:///tmp/sm73.dart:11:19)
#1      demo (file:///tmp/sm73.dart:27:32)
#2      main (file:///tmp/sm73.dart:37:3)
```
(I removed frames from the embedder calling `main`.)

This is the JavaScript output. It contains JavaScript stacks that needs to be converted into the above:
```
---- 123
b.x = ob;
b.x has value 123
TypeError: 123: type 'int' is not a subtype of type 'String'

    at Rti._asString [as _as] (/tmp/sm73.dart.js:1324:93)
    at Rti._installSpecializedAsCheck (/tmp/sm73.dart.js:1154:22)
    at NullBox.set$x (/tmp/sm73.dart.js:2847:30)
    at Object.demo (/tmp/sm73.dart.js:2404:13)
    at main (/tmp/sm73.dart.js:2425:9)
TypeError: null: type 'JSNull' is not a subtype of type 'String'

    at Rti._asString [as _as] (/tmp/sm73.dart.js:1324:93)
    at NullBox.get$x (/tmp/sm73.dart.js:2843:30)
    at Object.demo (/tmp/sm73.dart.js:2414:46)
    at main (/tmp/sm73.dart.js:2425:9)
---- xyz
TypeError: "xyz": type 'String' is not a subtype of type 'int'

    at Object._asInt (/tmp/sm73.dart.js:1294:90)
    at LateIntBox.set$x (/tmp/sm73.dart.js:2835:9)
    at Object.demo (/tmp/sm73.dart.js:2404:13)
    at main (/tmp/sm73.dart.js:2426:9)
LateInitializationError: Field 'x' has not been initialized.

    at Object.throwLateFieldNI (/tmp/sm73.dart.js:2450:74)
    at LateIntBox.get$x (/tmp/sm73.dart.js:2831:21)
    at Object.demo (/tmp/sm73.dart.js:2414:46)
    at main (/tmp/sm73.dart.js:2426:9)
b.x = ob;
TypeError: null: type 'JSNull' is not a subtype of type 'String'

    at Rti._asString [as _as] (/tmp/sm73.dart.js:1324:93)
    at NullBox.get$x (/tmp/sm73.dart.js:2843:30)
    at Object.demo (/tmp/sm73.dart.js:2414:46)
    at main (/tmp/sm73.dart.js:2426:9)
```
(I expect we would mark `Rti._asString` etc as hidden.)

**Comment by szuend** [comment]
The `NullBox` can be expressed with the current proposal but not for `LateIntBox`:

```
---- xyz
type 'String' is not a subtype of type 'int' of 'value'
#0      LateIntBox.x= (file:///tmp/sm73.dart:7:18)
#1      demo (file:///tmp/sm73.dart:20:9)
#2      main (file:///tmp/sm73.dart:37:3)

LateInitializationError: Field 'x' has not been initialized.
#0      LateIntBox.x (file:///tmp/sm73.dart)
#1      demo (file:///tmp/sm73.dart:27:32)
#2      main (file:///tmp/sm73.dart:37:3)
```

A couple of (unstructured) thoughts on this:

* These are purely synthetic frames inserted (I assume) to helper developers even though there is no actual real function in the  original source other then the generated getters/setters.
* The debugging behavior is a bit odd. Lets say we have "pause on exception" enabled and we pause in the `LateIntBox.x` getter/setter:
  * First  of all, for this to cleanly work, the dart compiler also has to emit mappings that are consistent with the synthetic scopes, meaning there needs to be multiple mapping points from the generated getters/setters, that all point to the `x` in `late final int x;` (so they are inside the synthetic scope).
  * There is nothing to actually "step" through. We'd be paused on a property declaration as there is no original code to look at. No local variables. Expression evaluation from an original source point of view is also odd, since it looks like you are inside a "class declaration scope" and not any function.
  * Setting a breakpoint on `late final int x;` would set N breakpoints in the generated getters/setters, depending on all the mappings pointing back to the `late final int x;`. This may or may not be expected. Although setting two breakpoints, one in the getter, and one in the setter, would be great IMO!
* The scopes tree currently has the nice property that nesting and finding the inner-most scope can be done purely based off the source position. Overlapping sibling scopes would break that and finding the inner-most scope containing a source position becomes ambiguous. This is not a problem if you start from a generated position, as you can disambiguate via the generated range pointing at the right original scope.
* I'm unsure if such synthetic scopes also would need to be marked as such via a new flag. To indicate that the scope doesn't actually correspond to anything "callable" in the source language. I don't think its needed.
* Encoding wise, we'd have to either:
  * Turn line/column into signed VLQs to allow going backwards. Paying for the sign-bit in each start/end item for this edge case is rather expensive.
  * Add a new item that can move the line/column cursor backwards. So you'd encode this is as: `<start item><end item><move cursor back item><start item><end item>`. This would probably be my preferred approach if we have to go this route, but unsure.

As a workaround, the Dart compiler could emit a single original scope with the name `LateIntBox.x get/set` that is used for both. I'd personally not have expected any frame with `LateIntBox.x` given that there is no actual function in the Dart code but Dart users would probably expect it?

**Comment by rakudrama** [comment]
My main concern is that the Dart VM produces a stack trace containing the getter / setter.
We would like dart2js and dart2wasm to be able to do the same.

Late variables (top level, local, instance field) can have an initializer, which may or may not be used.
```dart
late num x = mightExplode();
late num y = x * x;
...
if (??) x = 100;
if (??) y = 20;
print(y); // might just load 20, or compute 100*100, or call mightExplode.
```
If `mightExplode()` captures a stack trace, the generated stack trace should be translated into one that contains the getters.

**Comment by rakudrama** [comment]
> As a workaround, the Dart compiler could emit a single original scope with the name `LateIntBox.x get/set` that is used for both.

This might work for this one example. We are doing something a bit weird, can we _expect_ a tool that reads sourcemaps and writes new ones (e.g. wasm-opt, wasm-merge etc) to do the 'right thing' with this kind of workaround?

I think this is a general problem - one piece of syntax having multiple visible behaviours.

> I'd personally not have expected any frame with `LateIntBox.x` given that there is no actual function in the Dart code but Dart users would probably expect it?

That is what they get from debugging and stack traces on the Dart VM, so it should be what they see when compiling to JavaScript or WASM.

**Comment by rakudrama** [comment]
> I think this is a general problem - one piece of syntax having multiple visible behaviours.

Another example: a C++ class can have an implicit constructor, and implicit destructor, or both.
```c++
class X {
  private:
    A a;
  public:
};
```
If the constructor `A::A()` throws, or has a breakpoint, I would expect `X::X()` to be on the stack.
If the destructor `A::~A()` throws, or has a breakpoint, I would expect `X::~X()` to be on the stack.

There is no obvious original source scope for these two functions. If we chose `class X` for both, we have a similar situation.

Other languages have something similar - compiler-provided default implementations of multiple lifecycle methods.
Example: [Swift Equatable and Hashable](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0185-synthesize-equatable-hashable.md)

**Comment by szuend** [comment]
We discussed this offline quickly, but one approach could be to either:

- Add an optional "original name" to the generated range. This would be mutually exclusive with the range having a definition scope.
- Add a new "OriginalScopeNameItem" that can be nested inside a generated. Basically the same purpose.

This would allow us to "annotate" a generated range with a "isStackFrame: true" as "preserve this call frame with the 'original name', even though it does not have an actual "original scope". This would solve the general use case of compiler generated function that need to be preserved on the call stack.

One thing to note: We'd also have to add an optional "original name" to "Call site items" in the case where such a compiler generated function inlines authored code.
